// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheBulbProject.DataAccess.DataContext;

#nullable disable

namespace TheBulbProject.Migrations
{
    [DbContext(typeof(AppDBcontext))]
    [Migration("20250323143752_myfirstmigration")]
    partial class myfirstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("TheBulbProject.Domain.Model.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Options")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placeholder")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FormID");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("TheBulbProject.Domain.Model.FieldResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FormId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int>("RatingValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RespondedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmisionID")
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FieldID");

                    b.HasIndex("FormId");

                    b.HasIndex("SubmisionID");

                    b.ToTable("FieldResponses");
                });

            modelBuilder.Entity("TheBulbProject.Domain.Model.Form", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormType")
                        .HasColumnType("TEXT");

                    b.HasKey("FormId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("TheBulbProject.Domain.Model.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("TheBulbProject.Domain.Model.Field", b =>
                {
                    b.HasOne("TheBulbProject.Domain.Model.Form", null)
                        .WithMany("Fields")
                        .HasForeignKey("FormID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheBulbProject.Domain.Model.FieldResponse", b =>
                {
                    b.HasOne("TheBulbProject.Domain.Model.Field", null)
                        .WithMany("FieldResponses")
                        .HasForeignKey("FieldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBulbProject.Domain.Model.Form", null)
                        .WithMany("Responses")
                        .HasForeignKey("FormId");
                });

            modelBuilder.Entity("TheBulbProject.Domain.Model.Field", b =>
                {
                    b.Navigation("FieldResponses");
                });

            modelBuilder.Entity("TheBulbProject.Domain.Model.Form", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
